var vm = new Vue ({
  el: '#app',
  data: {
    grid: '16gl',
    isActive: 0,
    iconfontSize: 3.2,
    iconfontSizes: [1.6, 2, 2.4, 3.2, 4, 4.8, 6, 6.4, 7.2, 8, 9.6],
    iconfontStyle: {},
    isFocus: false,
    changeArrow: ['changeSize', 'f1', 'fb', 'ali_ite_cen'],
    tabs: [
      {id: 1, grid: '16gl', text: '16x16网格 线性'},
      {id: 2, grid: '16gf', text: '16x16网格 填充'},
      {id: 3, grid: '20gl', text: '20x20网格 线性'},
      {id: 4, grid: '20gf', text: '20x20网格 填充'},
      {id: 5, grid: '24gl', text: '24x24网格 线性'},
      {id: 6, grid: '24gf', text: '24x24网格 填充'}
    ],
    lists: [
      {
        id: 1,
        title: '1-1-Home & Building（首页 & 建筑）',
        content: [
          {id: 1, name: 'bricks', codename: '&#xe812;', tag: '砖,墙'},
          {id: 2, name: 'building', codename: '&#xe810;', tag: '建筑,大楼,大厦,楼宇'},
          {id: 3, name: 'building2', codename: '&#xe814;', tag: '建筑,大楼,大厦,楼宇'},
          {id: 4, name: 'building3', codename: '&#xe811;', tag: '建筑,大楼,大厦,楼宇'},
          {id: 5, name: 'church', codename: '&#xe813;', tag: '教堂,礼拜堂'},
          {id: 6, name: 'city', codename: '&#xe815;', tag: '城市,建筑,楼宇'},
          {id: 7, name: 'city2', codename: '&#xe817;', tag: '城市,建筑,楼宇'},
          {id: 8, name: 'city3', codename: '&#xe818;', tag: '城市,建筑,楼宇'},
          {id: 9, name: 'city4', codename: '&#xe81a;', tag: '城市,建筑,楼宇'},
          {id: 10, name: 'door', codename: '&#xe816;', tag: '门'},
          {id: 11, name: 'fence', codename: '&#xe825;', tag: '围栏,围墙,栅栏,篱笆,防护物'},
          {id: 12, name: 'gate', codename: '&#xe81d;', tag: '大门,栅栏门,围墙门'},
          {id: 13, name: 'gate2', codename: '&#xe81c;', tag: '大门,栅栏门,围墙门'},
          {id: 14, name: 'home', codename: '&#xe810;', tag: '家,首页'},
          {id: 15, name: 'home2', codename: '&#xe810;', tag: '家,首页'},
          {id: 16, name: 'home3', codename: '&#xe810;', tag: '家,首页'},
          {id: 17, name: 'home4', codename: '&#xe810;', tag: '家,首页'},
          {id: 18, name: 'home5', codename: '&#xe810;', tag: '家,首页'},
          {id: 19, name: 'home6', codename: '&#xe810;', tag: '家,首页'},
          {id: 20, name: 'home7', codename: '&#xe810;', tag: '家,首页'},
          {id: 21, name: 'home8', codename: '&#xe810;', tag: '家,首页'},
          {id: 22, name: 'home9', codename: '&#xe810;', tag: '家,首页'},
          {id: 23, name: 'home10', codename: '&#xe810;', tag: '家,首页'},
          {id: 24, name: 'home11', codename: '&#xe810;', tag: '家,首页'},
          {id: 25, name: 'home12', codename: '&#xe810;', tag: '家,首页'},
          {id: 26, name: 'hospital', codename: '&#xe810;', tag: '医院'},
          {id: 27, name: 'hotel', codename: '&#xe810;', tag: '酒店'},
          {id: 28, name: 'hotel2', codename: '&#xe810;', tag: '酒店'},
          {id: 29, name: 'school', codename: '&#xe810;', tag: '学校'},
          {id: 30, name: 'store', codename: '&#xe810;', tag: '商店,便利店'},
          {id: 31, name: 'store2', codename: '&#xe810;', tag: '商店,便利店'},
          {id: 32, name: 'window', codename: '&#xe810;', tag: '窗,窗口,窗户'}
        ]
      },        
      {
        id: 2,
        title: '2-1-Business & Stats（商业 & 业务 & 统计）',
        content: [
          {id: 1, name: 'chartBarDownward', codename: '&#xe810;', tag: '图表向下,业务统计,商业图表,统计,条形图'},
          {id: 2, name: 'chartBarUpward', codename: '&#xe810;', tag: '图表向上,业务统计,商业图表,统计,条形图'},
          {id: 3, name: 'chartLineDownward', codename: '&#xe810;', tag: '图表向下,业务统计,商业图表,统计,线形图,折线图'},
          {id: 4, name: 'chartLineUpward', codename: '&#xe810;', tag: '图表向上,业务统计,商业图表,统计,线形图,折线图'},
          {id: 5, name: 'chartPie', codename: '&#xe810;', tag: '饼状图,扇形图表,业务统计,商业图表,统计'},
          {id: 6, name: 'chartScatter', codename: '&#xe810;', tag: '散点图,散点图表,业务统计,商业图表,统计'}
        ]
      },
      {
        id: 3,
        title: '3-1-Shopping & Money（购物 & 金钱）',
        content: [
          {id: 1, name: 'bag', codename: '&#xe812;', tag: '袋子,购物袋'},
          {id: 2, name: 'bag2', codename: '&#xe810;', tag: '袋子,购物袋'},
          {id: 3, name: 'bagFull', codename: '&#xe814;', tag: '袋子,购物袋,袋满,装满袋子'},
          {id: 4, name: 'bagFull2', codename: '&#xe811;', tag: '袋子,购物袋,袋满,装满袋子'},
          {id: 5, name: 'banknote', codename: '&#xe813;', tag: '钞票,纸币,钱'},
          {id: 6, name: 'banknotes', codename: '&#xe815;', tag: '钞票,纸币,钱,一叠钞票,一叠纸币,一叠钱'},
          {id: 7, name: 'box', codename: '&#xe817;', tag: '箱,箱子,纸箱'},
          {id: 8, name: 'box2', codename: '&#xe818;', tag: '箱,箱子,纸箱'},
          {id: 9, name: 'cart', codename: '&#xe81a;', tag: '购物车,手推车'},
          {id: 10, name: 'cart2', codename: '&#xe816;', tag: '购物车,手推车'},
          {id: 11, name: 'cart3', codename: '&#xe825;', tag: '购物车,手推车'},
          {id: 12, name: 'cart4', codename: '&#xe81d;', tag: '购物车,手推车'},
          {id: 13, name: 'cart5', codename: '&#xe81c;', tag: '购物车,手推车'},
          {id: 14, name: 'cart6', codename: '&#xe810;', tag: '购物车,手推车'},
          {id: 15, name: 'cart7', codename: '&#xe810;', tag: '购物车,手推车'},
          {id: 16, name: 'cart8', codename: '&#xe810;', tag: '购物车,手推车'},
          {id: 17, name: 'cart9', codename: '&#xe810;', tag: '购物车,手推车'},
          {id: 18, name: 'cart10', codename: '&#xe810;', tag: '购物车,手推车'},
          {id: 19, name: 'cartFull', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 20, name: 'cartFull2', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 21, name: 'cartFull3', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 22, name: 'cartFull4', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 23, name: 'cartFull5', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 24, name: 'cartFull6', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 25, name: 'cartFull7', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 26, name: 'cartFull8', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 27, name: 'cartFull9', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 28, name: 'cartFull10', codename: '&#xe810;', tag: '购物车,手推车,购物车已满,手推车已满'},
          {id: 29, name: 'debitCard', codename: '&#xe810;', tag: '借记卡,银行卡,信用卡,储蓄卡'},
          {id: 30, name: 'receipt', codename: '&#xe810;', tag: '收据,发票,收入,账单'},
          {id: 31, name: 'receipt2', codename: '&#xe810;', tag: '收据,发票,收入,账单'},
          {id: 32, name: 'scanCode', codename: '&#xe810;', tag: '扫码,扫二维码,扫条形码'},
          {id: 33, name: 'scanCode2', codename: '&#xe810;', tag: '扫码,扫二维码,扫条形码'},
          {id: 34, name: 'tag', codename: '&#xe810;', tag: '标签'},
          {id: 35, name: 'tag2', codename: '&#xe810;', tag: '标签'},
          {id: 36, name: 'tags', codename: '&#xe810;', tag: '标签,多标签,多个标签'},
          {id: 37, name: 'tags2', codename: '&#xe810;', tag: '标签,多标签,多个标签'},
          {id: 38, name: 'tags3', codename: '&#xe810;', tag: '标签,多标签,多个标签'},
          {id: 39, name: 'tags4', codename: '&#xe810;', tag: '标签,多标签,多个标签'},
          {id: 40, name: 'wallet', codename: '&#xe810;', tag: '钱包,皮夹子'}
        ]
      },
      {
        id: 4,
        title: '4-2-2-Math & Arithmetic（数学 & 算术）',
        content: [
          {id: 1, name: 'minus', codename: '&#xe812;', tag: '减,减号,减法'},
          {id: 2, name: 'minusCircle', codename: '&#xe810;', tag: '减,减号,减法,删除,移除'},
          {id: 3, name: 'obelus', codename: '&#xe814;', tag: '除,除号,除法'},
          {id: 4, name: 'plus', codename: '&#xe811;', tag: '加,加号,加法,添加,新建'},
          {id: 5, name: 'plusCircle', codename: '&#xe813;', tag: '加,加号,加法,添加,新建'},
          {id: 6, name: 'plusMinus', codename: '&#xe815;', tag: '正负,正负号,加减,加减号'},
          {id: 7, name: 'percent', codename: '&#xe817;', tag: '百分比,百分号,百分数'}
        ]
      },
      {
        id: 5,
        title: '4-2-3-Medical & Health（医学 & 健康）',
        content: [
          {id: 1, name: 'heart', codename: '&#xe812;', tag: '心'},
          {id: 2, name: 'heartPulse', codename: '&#xe810;', tag: '心'},
          {id: 3, name: 'heartPulse2', codename: '&#xe814;', tag: '心脉搏,心电图,心率,脉搏'},
          {id: 4, name: 'pulse', codename: '&#xe811;', tag: '脉搏'}
        ]
      },
      {
        id: 6,
        title: '4-3-Books & Reading（书籍 & 阅读）',
        content: [
          {id: 1, name: 'bookmark', codename: '&#xe812;', tag: '书签'},
          {id: 2, name: 'bookmark2', codename: '&#xe810;', tag: '书签'},
          {id: 3, name: 'bookmarkMinus', codename: '&#xe814;', tag: '书签,删除书签,移除书签'},
          {id: 4, name: 'bookmarkPlus', codename: '&#xe811;', tag: '书签,删除书签,移除书签'},
          {id: 5, name: 'bookmarks', codename: '&#xe813;', tag: '书签,多书签'},
          {id: 6, name: 'bookmarks2', codename: '&#xe815;', tag: '书签,多书签'},
          {id: 7, name: 'label', codename: '&#xe817;', tag: '标签'},
          {id: 8, name: 'newspaper', codename: '&#xe817;', tag: '报纸,新闻,新闻页'},
          {id: 9, name: 'newspaper2', codename: '&#xe817;', tag: '报纸,新闻,新闻页'},
          {id: 10, name: 'newspaper3', codename: '&#xe817;', tag: '报纸,新闻,新闻页'},
          {id: 11, name: 'newspaper4', codename: '&#xe817;', tag: '报纸,新闻,新闻页'},
          {id: 12, name: 'newspapers', codename: '&#xe817;', tag: '报纸,新闻,新闻页,多份报纸,多则新闻'},
          {id: 13, name: 'newspapers2', codename: '&#xe817;', tag: '报纸,新闻,新闻页,多份报纸,多则新闻'}
        ]
      },
      {
        id: 7,
        title: '4-4-Achievements & Ranking（成就 & 排名）',
        content: [
          {id: 1, name: 'podium', codename: '&#xe812;', tag: '领奖台,排位'},
          {id: 2, name: 'podium2', codename: '&#xe810;', tag: '领奖台,排位'},
          {id: 3, name: 'podium3', codename: '&#xe814;', tag: '领奖台,排位'},
          {id: 4, name: 'star', codename: '&#xe811;', tag: '星星'},
          {id: 5, name: 'starEmpty', codename: '&#xe813;', tag: '星星,空星,虚线星'},
          {id: 6, name: 'starHalf', codename: '&#xe815;', tag: '星星,半星'}
        ]
      },
      {
        id: 8,
        title: '5-1-Communication（交流通信）',
        content: [
          {id: 1, name: 'atSign', codename: '&#xe812;', tag: '商用符号,@'},
          {id: 2, name: 'atSignCircle', codename: '&#xe810;', tag: '商用符号,@'},
          {id: 3, name: 'bubble', codename: '&#xe814;', tag: '聊天,信息,消息,气泡'},
          {id: 4, name: 'bubble2', codename: '&#xe811;', tag: '聊天,信息,消息,气泡'},
          {id: 5, name: 'bubble3', codename: '&#xe813;', tag: '聊天,信息,消息,气泡'},
          {id: 6, name: 'bubble4', codename: '&#xe815;', tag: '聊天,信息,消息,气泡'},
          {id: 7, name: 'bubbleDots', codename: '&#xe817;', tag: '聊天,信息,消息,气泡'},
          {id: 8, name: 'bubbleDots2', codename: '&#xe818;', tag: '聊天,信息,消息,气泡'},
          {id: 9, name: 'bubbleDots3', codename: '&#xe81a;', tag: '聊天,信息,消息,气泡'},
          {id: 10, name: 'bubbleDots4', codename: '&#xe816;', tag: '聊天,信息,消息,气泡'},
          {id: 11, name: 'bubbles', codename: '&#xe825;', tag: '聊天,信息,消息,气泡'},
          {id: 12, name: 'bubbles2', codename: '&#xe81d;', tag: '聊天,信息,消息,气泡'},
          {id: 13, name: 'bubbles3', codename: '&#xe81c;', tag: '聊天,信息,消息,气泡'},
          {id: 14, name: 'bubbles4', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 15, name: 'bubbles5', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 16, name: 'bubbles6', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 17, name: 'bubbles7', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 18, name: 'bubblesDots', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 19, name: 'bubblesDots2', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 20, name: 'bubblesDots3', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 21, name: 'bubblesDots4', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 22, name: 'bubblesDots5', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 23, name: 'bubblesDots6', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 24, name: 'bubblesDots7', codename: '&#xe810;', tag: '聊天,信息,消息,气泡'},
          {id: 25, name: 'deliveryFailure', codename: '&#xe810;', tag: '投递失败'},
          {id: 26, name: 'deliverySuccess', codename: '&#xe810;', tag: '投递成功'},
          {id: 27, name: 'deliveryWarning', codename: '&#xe810;', tag: '投递警告'},
          {id: 28, name: 'envelope', codename: '&#xe810;', tag: '信封,邮件,信息,消息'},
          {id: 29, name: 'envelope2', codename: '&#xe810;', tag: '信封,邮件,信息,消息'},
          {id: 30, name: 'envelopeCheck', codename: '&#xe810;', tag: '邮件,检查邮件'},
          {id: 31, name: 'envelopeCross', codename: '&#xe810;', tag: '邮件,错误邮件'},
          {id: 32, name: 'envelopeWarning', codename: '&#xe810;', tag: '邮件,警告邮件'},
          {id: 33, name: 'envelopeInfo', codename: '&#xe810;', tag: '邮件,信息邮件'},
          {id: 34, name: 'envelopeMinus', codename: '&#xe810;', tag: '邮件,删除邮件,移除邮件'},
          {id: 35, name: 'envelopeOpen', codename: '&#xe810;', tag: '打开信封,打开邮件,打开信息,打开消息'},
          {id: 36, name: 'envelopeOpen2', codename: '&#xe810;', tag: '打开信封,打开邮件,打开信息,打开消息'},
          {id: 37, name: 'envelopePlus', codename: '&#xe810;', tag: '邮件,添加邮件,新建邮件'},
          {id: 38, name: 'envelopeSent', codename: '&#xe810;', tag: '发送邮件,发送信息'},
          {id: 39, name: 'envelopeSent2', codename: '&#xe810;', tag: '发送邮件,发送信息'},
          {id: 40, name: 'envelopeSent3', codename: '&#xe810;', tag: '发送邮件,发送信息'},
          {id: 41, name: 'envelopeSent4', codename: '&#xe810;', tag: '发送邮件,发送信息'},
          {id: 42, name: 'envelopeSent5', codename: '&#xe810;', tag: '发送邮件,发送信息'},
          {id: 43, name: 'mailboxEmpty', codename: '&#xe810;', tag: '邮箱,邮箱空,空邮箱'},
          {id: 44, name: 'mailboxFull', codename: '&#xe810;', tag: '邮箱,邮箱满,满邮箱'},
          {id: 45, name: 'missedIncoming', codename: '&#xe810;', tag: '未接打进,打进未接'},
          {id: 46, name: 'missedIncoming2', codename: '&#xe810;', tag: '未接打进,打进未接'},
          {id: 47, name: 'missedOutgoing', codename: '&#xe810;', tag: '未接打出,打出未接'},
          {id: 48, name: 'missedOutgoing2', codename: '&#xe810;', tag: '未接打出,打出未接'},
          {id: 49, name: 'paperclip', codename: '&#xe810;', tag: '回形针,曲别针'},
          {id: 50, name: 'paperclip2', codename: '&#xe810;', tag: '回形针,曲别针'},
          {id: 51, name: 'paperclipCircle', codename: '&#xe810;', tag: '回形针,曲别针'},
          {id: 52, name: 'paperclipCircle2', codename: '&#xe810;', tag: '回形针,曲别针'},
          {id: 53, name: 'paperPlane', codename: '&#xe810;', tag: '纸飞机'},
          {id: 54, name: 'phone24h', codename: '&#xe810;', tag: '电话24小时,24小时电话'},
          {id: 55, name: 'phoneBook', codename: '&#xe810;', tag: '电话薄,电话本'},
          {id: 56, name: 'phoneBubble', codename: '&#xe810;', tag: '电话聊天,电话气泡'},
          {id: 57, name: 'phoneCross', codename: '&#xe810;', tag: '电话打叉'},
          {id: 58, name: 'phoneEnd', codename: '&#xe810;', tag: '挂机,结束通话,结束呼叫'},
          {id: 59, name: 'phoneIncoming', codename: '&#xe810;', tag: '电话呼入,呼入'},
          {id: 60, name: 'phoneInOut', codename: '&#xe810;', tag: '电话呼入呼出,呼入呼出'},
          {id: 61, name: 'phoneLock', codename: '&#xe810;', tag: '电话锁,电话锁住'},
          {id: 62, name: 'phoneLoudspeaker', codename: '&#xe810;', tag: '电话扬声器,电话呼叫'},
          {id: 63, name: 'phoneMinus', codename: '&#xe810;', tag: '移除电话'},
          {id: 64, name: 'phoneOutgoing', codename: '&#xe810;', tag: '电话呼出,呼出'},
          {id: 65, name: 'phonePause', codename: '&#xe810;', tag: '电话暂停,通话暂停,呼叫暂停'},
          {id: 66, name: 'phonePlus', codename: '&#xe810;', tag: '添加电话'},
          {id: 67, name: 'phoneSip', codename: '&#xe810;', tag: '电话SIP,SIP'},
          {id: 68, name: 'phoneTime', codename: '&#xe810;', tag: '电话时间,热线时间,客服时间'},
          {id: 69, name: 'phoneUser', codename: '&#xe810;', tag: '电话用户'},
          {id: 70, name: 'phoneVoicemail', codename: '&#xe810;', tag: '电话语音信箱'},
          {id: 71, name: 'reply', codename: '&#xe810;', tag: '回复'},
          {id: 72, name: 'replyAll', codename: '&#xe810;', tag: '回复所有,回复全部'},
          {id: 73, name: 'telephone', codename: '&#xe810;', tag: '电话,电话机,话筒'},
          {id: 74, name: 'telephone2', codename: '&#xe810;', tag: '电话,电话机'},
          {id: 75, name: 'telephone3', codename: '&#xe810;', tag: '电话,电话机'},
          {id: 76, name: 'telephoneKeypad', codename: '&#xe810;', tag: '电话键盘,电话拨号盘'},
          {id: 77, name: 'telephoneKeypad2', codename: '&#xe810;', tag: '电话键盘,电话拨号盘'},
          {id: 78, name: 'telephoneKeypad3', codename: '&#xe810;', tag: '电话键盘,电话拨号盘'},
          {id: 79, name: 'telephoneKeypad4', codename: '&#xe810;', tag: '电话键盘,电话拨号盘'},
          {id: 80, name: 'voicemail', codename: '&#xe810;', tag: '语音信箱'}
        ]
      },
      {
        id: 9,
        title: '5-2-Alert & Tip（警告 & 提示）',
        content: [
          {id: 1, name: 'check', codename: '&#xe812;', tag: '检查,核对,打勾,成功'},
          {id: 2, name: 'cross', codename: '&#xe810;', tag: '打叉,交叉,关闭,清除,乘,乘号,乘法'},
          {id: 3, name: 'errorCircle', codename: '&#xe814;', tag: '错误'},
          {id: 4, name: 'exclamation', codename: '&#xe811;', tag: '感叹号'},
          {id: 5, name: 'infoCircle', codename: '&#xe813;', tag: '信息'},
          {id: 6, name: 'question', codename: '&#xe815;', tag: '问题,问号'},
          {id: 7, name: 'questionCircle', codename: '&#xe815;', tag: '问题,问号'},
          {id: 8, name: 'successCircle', codename: '&#xe815;', tag: '成功,检查,核对,打勾'},
          {id: 9, name: 'warningCircle', codename: '&#xe815;', tag: '警告,感叹号'}
        ]
      },
      {
        id: 10,
        title: '5-3-Networks & Web（网络）',
        content: [
          {id: 1, name: 'branches', codename: '&#xe812;', tag: '分支,分支机构'},
          {id: 2, name: 'network', codename: '&#xe810;', tag: '网络'},
          {id: 3, name: 'network2', codename: '&#xe814;', tag: '网络'},
          {id: 4, name: 'repost', codename: '&#xe811;', tag: '转发,分享'},
          {id: 5, name: 'repost2', codename: '&#xe813;', tag: '转发,分享'},
          {id: 6, name: 'share', codename: '&#xe815;', tag: '分享'},
          {id: 7, name: 'share2', codename: '&#xe815;', tag: '分享'},
          {id: 8, name: 'share3', codename: '&#xe815;', tag: '分享'}
        ]
      },
      {
        id: 11,
        title: '5-4-Computers & Electronics（计算机 & 电子学）',
        content: [
          {id: 1, name: 'appsBig', codename: '&#xe812;', tag: '应用,大网格,网格列表'},
          {id: 2, name: 'appsBig2', codename: '&#xe810;', tag: '应用,大网格,网格列表'},
          {id: 3, name: 'appsBig3', codename: '&#xe814;', tag: '应用,大网格,网格列表'},
          {id: 4, name: 'appsBig4', codename: '&#xe811;', tag: '应用,大网格,网格列表'},
          {id: 5, name: 'appsBig5', codename: '&#xe813;', tag: '应用,大网格,网格列表'},
          {id: 6, name: 'appsBig6', codename: '&#xe815;', tag: '应用,大网格,网格列表'},
          {id: 7, name: 'appsBig7', codename: '&#xe815;', tag: '应用,大网格,网格列表'},
          {id: 8, name: 'appsSelect', codename: '&#xe815;', tag: '框选应用'},
          {id: 9, name: 'appsSelect2', codename: '&#xe815;', tag: '框选应用'},
          {id: 10, name: 'appsSmall', codename: '&#xe815;', tag: '应用,小网格,网格列表'},
          {id: 11, name: 'appsSmall2', codename: '&#xe815;', tag: '应用,小网格,网格列表'},
          {id: 12, name: 'appsSmall3', codename: '&#xe815;', tag: '应用,小网格,网格列表'},
          {id: 13, name: 'appsSmall4', codename: '&#xe815;', tag: '应用,小网格,网格列表'},
          {id: 14, name: 'code', codename: '&#xe815;', tag: '代码,插入代码'},
          {id: 15, name: 'floppyDisk', codename: '&#xe815;', tag: '软盘,磁盘'},
          {id: 16, name: 'gear', codename: '&#xe815;', tag: '齿轮,设置'},
          {id: 17, name: 'gear2', codename: '&#xe815;', tag: '齿轮,设置'},
          {id: 18, name: 'gear3', codename: '&#xe815;', tag: '齿轮,设置'},
          {id: 19, name: 'gear4', codename: '&#xe815;', tag: '齿轮,设置'},
          {id: 20, name: 'monitor', codename: '&#xe815;', tag: '显示器'},
          {id: 21, name: 'monitorSystem', codename: '&#xe815;', tag: '显示器,监控系统'},
          {id: 22, name: 'pointer', codename: '&#xe815;', tag: '指针,鼠标指针'},
          {id: 23, name: 'printer', codename: '&#xe815;', tag: '打印机,打印'},
          {id: 24, name: 'select', codename: '&#xe815;', tag: '选择,框选'},
          {id: 25, name: 'shredder', codename: '&#xe815;', tag: '碎纸机'}
        ]
      },
      {
        id: 12,
        title: '5-5-Security（安全性）',
        content: [
          {id: 1, name: 'lock', codename: '&#xe812;', tag: '锁,锁上,锁住'},
          {id: 2, name: 'lock2', codename: '&#xe810;', tag: '锁,锁上,锁住'},
          {id: 3, name: 'shield', codename: '&#xe814;', tag: '盾,护罩,保护'},
          {id: 4, name: 'shieldCheck', codename: '&#xe811;', tag: '盾,护罩,保护,安全检测,检测安全性'},
          {id: 5, name: 'shieldCross', codename: '&#xe813;', tag: '盾,护罩,保护,安全检测错误,安全隐患,不安全'},
          {id: 6, name: 'shieldInfo', codename: '&#xe815;', tag: '盾,护罩,保护,安全信息'},
          {id: 7, name: 'shieldWarning', codename: '&#xe815;', tag: '盾,护罩,保护,安全警报,安全警告'},
          {id: 8, name: 'unlock', codename: '&#xe815;', tag: '解锁,开锁,开启'},
          {id: 9, name: 'unlock2', codename: '&#xe815;', tag: '解锁,开锁,开启'},
          {id: 10, name: 'unlock3', codename: '&#xe815;', tag: '解锁,开锁,开启'},
          {id: 11, name: 'unlock3', codename: '&#xe815;', tag: '解锁,开锁,开启'}
        ]
      },
      {
        id: 13,
        title: '6-1-Photos & Videos（照片 & 视频）',
        content: [
          {id: 1, name: 'camera', codename: '&#xe812;', tag: '相机,照相机,摄影机'},
          {id: 2, name: 'camera2', codename: '&#xe810;', tag: '相机,照相机,摄影机'},
          {id: 3, name: 'camera3', codename: '&#xe814;', tag: '相机,照相机,摄影机'},
          {id: 4, name: 'focalPoint', codename: '&#xe811;', tag: '对焦,焦点'},
          {id: 5, name: 'photoAlbum', codename: '&#xe813;', tag: '相册,相簿,照片集,图片集'},
          {id: 6, name: 'photoAlbum2', codename: '&#xe815;', tag: '相册,相簿,照片集,图片集'},
          {id: 7, name: 'picture', codename: '&#xe815;', tag: '图片'},
          {id: 8, name: 'pictures', codename: '&#xe815;', tag: '图片,批量图片'},
          {id: 9, name: 'pictureSplit', codename: '&#xe815;', tag: '图片裂开,图片加载失败,图片崩了'},
          {id: 10, name: 'shutter', codename: '&#xe815;', tag: '快门,相机快门'},
          {id: 11, name: 'shutter2', codename: '&#xe815;', tag: '快门,相机快门'},
          {id: 12, name: 'theater', codename: '&#xe815;', tag: '剧场,戏剧,面具'},
          {id: 13, name: 'videoAlbum', codename: '&#xe815;', tag: '视频专辑,电影专辑,电子影集'},
          {id: 14, name: 'videoAlbum2', codename: '&#xe815;', tag: '视频专辑,电影专辑,电子影集'},
          {id: 15, name: 'videoCamera', codename: '&#xe815;', tag: '摄像机,录像机'}
        ]
      },
      {
        id: 14,
        title: '6-2-Sound & Music（声音 & 音乐）',
        content: [
          {id: 1, name: 'bell', codename: '&#xe812;', tag: '铃铛,钟'},
          {id: 2, name: 'equalizer', codename: '&#xe810;', tag: '均衡器,设置'},
          {id: 3, name: 'equalizer2', codename: '&#xe814;', tag: '均衡器,设置'},
          {id: 4, name: 'headphones', codename: '&#xe811;', tag: '耳机,耳麦,头戴式耳机'},
          {id: 5, name: 'headset', codename: '&#xe813;', tag: '耳机,耳麦,头戴式耳机'},
          {id: 6, name: 'megaphone', codename: '&#xe815;', tag: '扩音器,公告'},
          {id: 7, name: 'mic', codename: '&#xe815;', tag: '麦克风,话筒'},
          {id: 8, name: 'micDisable', codename: '&#xe815;', tag: '禁用麦克风,禁用话筒'},
          {id: 9, name: 'musicAlbum', codename: '&#xe815;', tag: '音乐专辑,音频影集'},
          {id: 10, name: 'musicAlbum2', codename: '&#xe815;', tag: '音乐专辑,音频影集'},
          {id: 11, name: 'volumeCross', codename: '&#xe815;', tag: '音量,禁用音量,音量打叉'},
          {id: 12, name: 'volumeDisable', codename: '&#xe815;', tag: '音量,禁用音量'},
          {id: 13, name: 'volumeHigh', codename: '&#xe815;', tag: '音量,高音量'},
          {id: 14, name: 'volumeLow', codename: '&#xe815;', tag: '音量,低音量'},
          {id: 15, name: 'volumeMiddle', codename: '&#xe815;', tag: '音量,中音量'},
          {id: 16, name: 'volumeZero', codename: '&#xe815;', tag: '音量,零音量,无音量'}
        ]
      },
      {
        id: 15,
        title: '6-3-Playback Controls（播放控件）',
        content: [
          {id: 1, name: 'backward', codename: '&#xe812;', tag: '向后,快退'},
          {id: 2, name: 'backwardCircle', codename: '&#xe810;', tag: '向后,快退'},
          {id: 3, name: 'backwardSquare', codename: '&#xe814;', tag: '向后,快退'},
          {id: 4, name: 'ejectDown', codename: '&#xe811;', tag: '弹出,弹出按钮,向下弹出,向下弹出按钮,打开文件'},
          {id: 5, name: 'ejectDownCircle', codename: '&#xe813;', tag: '弹出,弹出按钮,向下弹出,向下弹出按钮,打开文件'},
          {id: 6, name: 'ejectDownSquare', codename: '&#xe815;', tag: '弹出,弹出按钮,向下弹出,向下弹出按钮,打开文件'},
          {id: 7, name: 'ejectUp', codename: '&#xe817;', tag: '弹出,弹出按钮,向上弹出,向上弹出按钮,打开文件'},
          {id: 8, name: 'ejectUpCircle', codename: '&#xe818;', tag: '弹出,弹出按钮,向上弹出,向上弹出按钮,打开文件'},
          {id: 9, name: 'ejectUpSquare', codename: '&#xe81a;', tag: '弹出,弹出按钮,向上弹出,向上弹出按钮,打开文件'},
          {id: 10, name: 'first', codename: '&#xe816;', tag: '第一,开头'},
          {id: 11, name: 'firstCircle', codename: '&#xe825;', tag: '第一,开头'},
          {id: 12, name: 'firstSquare', codename: '&#xe81d;', tag: '第一,开头'},
          {id: 13, name: 'firstFrame', codename: '&#xe81c;', tag: '第一帧,首帧'},
          {id: 14, name: 'firstFrameCircle', codename: '&#xe810;', tag: '第一帧,首帧'},
          {id: 15, name: 'firstFrameSquare', codename: '&#xe810;', tag: '第一帧,首帧'},
          {id: 16, name: 'forward', codename: '&#xe810;', tag: '向前,快进'},
          {id: 17, name: 'forwardCircle', codename: '&#xe810;', tag: '向前,快进'},
          {id: 18, name: 'forwardSquare', codename: '&#xe810;', tag: '向前,快进'},
          {id: 19, name: 'fullScreenEnter', codename: '&#xe810;', tag: '全屏,进入全屏'},
          {id: 20, name: 'fullScreenEnter2', codename: '&#xe810;', tag: '全屏,进入全屏'},
          {id: 21, name: 'fullScreenEnter3', codename: '&#xe810;', tag: '全屏,进入全屏'},
          {id: 22, name: 'fullScreenExit', codename: '&#xe810;', tag: '退出全屏'},
          {id: 23, name: 'fullScreenExit2', codename: '&#xe810;', tag: '退出全屏'},
          {id: 24, name: 'fullScreenExit3', codename: '&#xe810;', tag: '退出全屏'},
          {id: 25, name: 'last', codename: '&#xe810;', tag: '最后,末尾'},
          {id: 26, name: 'lastCircle', codename: '&#xe810;', tag: '最后,末尾'},
          {id: 27, name: 'lastSquare', codename: '&#xe810;', tag: '最后,末尾'},
          {id: 28, name: 'lastFrame', codename: '&#xe810;', tag: '最后帧,末尾帧'},
          {id: 29, name: 'lastFrameCircle', codename: '&#xe810;', tag: '最后帧,末尾帧'},
          {id: 30, name: 'lastFrameSquare', codename: '&#xe810;', tag: '最后帧,末尾帧'},
          {id: 31, name: 'minimization', codename: '&#xe810;', tag: '最小化,窗口最小化'},
          {id: 32, name: 'minimize', codename: '&#xe810;', tag: '小化,窗口小化,向下还原'},
          {id: 33, name: 'minimize2', codename: '&#xe810;', tag: '小化,窗口小化,向下还原'},
          {id: 34, name: 'next', codename: '&#xe810;', tag: '下一个,下一个按钮'},
          {id: 35, name: 'nextCircle', codename: '&#xe810;', tag: '下一个,下一个按钮'},
          {id: 36, name: 'nextSquare', codename: '&#xe810;', tag: '下一个,下一个按钮'},
          {id: 37, name: 'nextFrame', codename: '&#xe810;', tag: '下一帧,下一帧按钮'},
          {id: 38, name: 'nextFrameCircle', codename: '&#xe810;', tag: '下一帧,下一帧按钮'},
          {id: 39, name: 'nextFrameSquare', codename: '&#xe810;', tag: '下一帧,下一帧按钮'},
          {id: 40, name: 'pause', codename: '&#xe810;', tag: '暂停,暂停按钮'},
          {id: 41, name: 'pause2', codename: '&#xe810;', tag: '暂停,暂停按钮'},
          {id: 42, name: 'pauseCircle', codename: '&#xe810;', tag: '暂停,暂停按钮'},
          {id: 43, name: 'pauseSquare', codename: '&#xe810;', tag: '暂停,暂停按钮'},
          {id: 44, name: 'play', codename: '&#xe810;', tag: '播放,播放按钮'},
          {id: 45, name: 'playCircle', codename: '&#xe810;', tag: '播放,播放按钮'},
          {id: 46, name: 'playSquare', codename: '&#xe810;', tag: '播放,播放按钮'},
          {id: 47, name: 'playlist', codename: '&#xe810;', tag: '播放列表'},
          {id: 48, name: 'playlist2', codename: '&#xe810;', tag: '播放列表'},
          {id: 49, name: 'playlist3', codename: '&#xe810;', tag: '播放列表'},
          {id: 50, name: 'playlist4', codename: '&#xe810;', tag: '播放列表'},
          {id: 51, name: 'playlistHeart', codename: '&#xe810;', tag: '播放列表,播放收藏列表,播放喜欢列表'},
          {id: 52, name: 'playlistHeart2', codename: '&#xe810;', tag: '播放列表,播放收藏列表,播放喜欢列表'},
          {id: 53, name: 'playlistHeart3', codename: '&#xe810;', tag: '播放列表,播放收藏列表,播放喜欢列表'},
          {id: 54, name: 'playlistHeart4', codename: '&#xe810;', tag: '播放列表,播放收藏列表,播放喜欢列表'},
          {id: 55, name: 'playlistMusic', codename: '&#xe810;', tag: '播放列表,音乐播放列表'},
          {id: 56, name: 'playlistMusic2', codename: '&#xe810;', tag: '播放列表,音乐播放列表'},
          {id: 57, name: 'playlistMusic3', codename: '&#xe810;', tag: '播放列表,音乐播放列表'},
          {id: 58, name: 'playlistMusic4', codename: '&#xe810;', tag: '播放列表,音乐播放列表'},
          {id: 59, name: 'playlistMusic5', codename: '&#xe810;', tag: '播放列表,音乐播放列表'},
          {id: 60, name: 'playlistVideo', codename: '&#xe810;', tag: '播放列表,视频播放列表'},
          {id: 61, name: 'playlistVideo2', codename: '&#xe810;', tag: '播放列表,视频播放列表'},
          {id: 62, name: 'previous', codename: '&#xe810;', tag: '上一个,上一个按钮'},
          {id: 63, name: 'previousCircle', codename: '&#xe810;', tag: '上一个,上一个按钮'},
          {id: 64, name: 'previousSquare', codename: '&#xe810;', tag: '上一个,上一个按钮'},
          {id: 65, name: 'previousFrame', codename: '&#xe810;', tag: '上一帧,上一帧按钮'},
          {id: 66, name: 'previousFrameCircle', codename: '&#xe810;', tag: '上一帧,上一帧按钮'},
          {id: 67, name: 'previousFrameSquare', codename: '&#xe810;', tag: '上一帧,上一帧按钮'},
          {id: 68, name: 'record', codename: '&#xe810;', tag: '记录,记载,录音,录像'},
          {id: 69, name: 'recordCircle', codename: '&#xe810;', tag: '记录,记载,录音,录像'},
          {id: 70, name: 'recordSquare', codename: '&#xe810;', tag: '记录,记载,录音,录像'},
          {id: 71, name: 'repeat', codename: '&#xe810;', tag: '重复,循环,重复播放,循环播放'},
          {id: 72, name: 'repeat2', codename: '&#xe810;', tag: '重复,循环,重复播放,循环播放'},
          {id: 73, name: 'repeatDot', codename: '&#xe810;', tag: '重复,循环,重复播放,循环播放'},
          {id: 74, name: 'repeatDot2', codename: '&#xe810;', tag: '重复,循环,重复播放,循环播放'},
          {id: 75, name: 'repeatInfinite', codename: '&#xe810;', tag: '重复,循环,无限循环'},
          {id: 76, name: 'repeatInfinite2', codename: '&#xe810;', tag: '重复,循环,无限循环'},
          {id: 77, name: 'repeatOnce', codename: '&#xe810;', tag: '重复,循环,重复一遍,重复一次,单曲循环'},
          {id: 78, name: 'repeatOnce2', codename: '&#xe810;', tag: '重复,循环,重复一遍,重复一次,单曲循环'},
          {id: 79, name: 'shuffle', codename: '&#xe810;', tag: '洗牌,随机,随机播放'},
          {id: 80, name: 'stop', codename: '&#xe810;', tag: '停止,停止按钮'},
          {id: 81, name: 'stopCircle', codename: '&#xe810;', tag: '停止,停止按钮'},
          {id: 82, name: 'stopSquare', codename: '&#xe810;', tag: '停止,停止按钮'}
        ]
      },
      {
        id: 16,
        title: '7-1-Design & Drawing（设计 & 绘图）',
        content: [
          {id: 1, name: 'changeOrder', codename: '&#xe812;', tag: '更改顺序,重新排序'},
          {id: 2, name: 'circle', codename: '&#xe810;', tag: '圆,圆形'},
          {id: 3, name: 'eye', codename: '&#xe814;', tag: '眼睛,显示,预览,查看'},
          {id: 4, name: 'eye2', codename: '&#xe811;', tag: '眼睛,显示,预览,查看'},
          {id: 5, name: 'eyeHide', codename: '&#xe813;', tag: '眼睛,隐藏,禁止预览,禁止查看'},
          {id: 6, name: 'eyeHide2', codename: '&#xe815;', tag: '眼睛,隐藏,禁止预览,禁止查看'},
          {id: 7, name: 'grid', codename: '&#xe815;', tag: '网格'},
          {id: 8, name: 'rectangle', codename: '&#xe815;', tag: '矩形,长方形'},
          {id: 9, name: 'square', codename: '&#xe815;', tag: '正方形,方形'},
          {id: 10, name: 'zoomIn', codename: '&#xe815;', tag: '放大'},
          {id: 11, name: 'zoomOut', codename: '&#xe815;', tag: '缩小'}
        ]
      },
      {
        id: 17,
        title: '7-2-Files & Documents（文件 & 文档）',
        content: [
          {id: 1, name: 'archiveBox', codename: '&#xe812;', tag: '档案盒,档案箱'},
          {id: 2, name: 'clipboardChecklist', codename: '&#xe814;', tag: '剪贴板检查清单,检查清单'},
          {id: 3, name: 'clipboardDown', codename: '&#xe811;', tag: '剪贴板,剪贴板向下,剪贴板下载'},
          {id: 4, name: 'clipboardEmpty', codename: '&#xe813;', tag: '剪贴板,空剪贴板'},
          {id: 5, name: 'clipboardLeft', codename: '&#xe815;', tag: '剪贴板,剪贴板向左'},
          {id: 6, name: 'clipboardList', codename: '&#xe815;', tag: '剪贴板清单,清单,列表'},
          {id: 7, name: 'clipboardText', codename: '&#xe815;', tag: '剪贴板文本'},
          {id: 8, name: 'clipboardCheck', codename: '&#xe810;', tag: '剪贴板检查'},
          {id: 9, name: 'clipboardWarning', codename: '&#xe815;', tag: '剪贴板警告'},
          {id: 10, name: 'drawer', codename: '&#xe815;', tag: '抽屉'},
          {id: 11, name: 'fileEmpty', codename: '&#xe815;', tag: '文件,空文件'},
          {id: 12, name: 'filePencil', codename: '&#xe815;', tag: '文件,文件铅笔,编写,编辑'},
          {id: 13, name: 'filePencil2', codename: '&#xe815;', tag: '文件,文件铅笔,编写,编辑'},
          {id: 14, name: 'fileText', codename: '&#xe815;', tag: '文件,文本文件'},
          {id: 15, name: 'folder', codename: '&#xe815;', tag: '文件夹'},
          {id: 16, name: 'folder2', codename: '&#xe815;', tag: '文件夹'},
          {id: 17, name: 'folder3', codename: '&#xe815;', tag: '文件夹'},
          {id: 18, name: 'folder4', codename: '&#xe815;', tag: '文件夹'},
          {id: 19, name: 'folderHeart', codename: '&#xe815;', tag: '文件夹,喜欢文件夹,收藏文件夹'},
          {id: 20, name: 'folderMinus', codename: '&#xe815;', tag: '删除文件夹,移除文件夹'},
          {id: 21, name: 'folderOpen', codename: '&#xe815;', tag: '打开文件夹,展开文件夹'},
          {id: 22, name: 'folderPlus', codename: '&#xe815;', tag: '添加文件夹,创建文件夹'},
          {id: 23, name: 'folderShare', codename: '&#xe815;', tag: '文件夹,共享文件夹'},
          {id: 24, name: 'folderStar', codename: '&#xe815;', tag: '文件夹,星际文件夹,收藏文件夹'}
        ]
      },
      {
        id: 18,
        title: '7-3-Filtering & Screening & Search（过滤 & 筛选 & 搜索）',
        content: [
          {id: 1, name: 'funnel', codename: '&#xe812;', tag: '漏斗,筛选,过滤'},
          {id: 2, name: 'lookup', codename: '&#xe810;', tag: '查找,分类查找'},
          {id: 3, name: 'lookup2', codename: '&#xe814;', tag: '查找,分类查找'},
          {id: 4, name: 'search', codename: '&#xe811;', tag: '搜索,放大镜'},
          {id: 5, name: 'search2', codename: '&#xe813;', tag: '搜索,放大镜'}
        ]
      },
      {
        id: 19,
        title: '7-4-Typography & TextEditor（排版 & 文本编辑）',
        content: [
          {id: 1, name: 'bold', codename: '&#xe812;', tag: '加粗'},
          {id: 2, name: 'bold2', codename: '&#xe810;', tag: '加粗'},
          {id: 3, name: 'borderAll', codename: '&#xe814;', tag: '所有边框'},
          {id: 4, name: 'borderBottom', codename: '&#xe811;', tag: '下边框线'},
          {id: 5, name: 'borderGroup', codename: '&#xe813;', tag: '边框线组'},
          {id: 6, name: 'borderInside', codename: '&#xe815;', tag: '内部边框线'},
          {id: 7, name: 'borderInsideCol', codename: '&#xe817;', tag: '内部竖边框线'},
          {id: 8, name: 'borderInsideRow', codename: '&#xe818;', tag: '内部横边框线'},
          {id: 9, name: 'borderLeft', codename: '&#xe81a;', tag: '左边框线'},
          {id: 10, name: 'borderNone', codename: '&#xe816;', tag: '无边框线'},
          {id: 11, name: 'borderObliqueDown', codename: '&#xe825;', tag: '斜向下边框线'},
          {id: 12, name: 'borderObliqueUp', codename: '&#xe81d;', tag: '斜向上边框线'},
          {id: 13, name: 'borderOutside', codename: '&#xe81c;', tag: '外部边框线'},
          {id: 14, name: 'borderRight', codename: '&#xe810;', tag: '右边框线'},
          {id: 15, name: 'borderTop', codename: '&#xe810;', tag: '上边框线'},
          {id: 16, name: 'checklist', codename: '&#xe810;', tag: '检查清单,选择列表'},
          {id: 17, name: 'checklist2', codename: '&#xe810;', tag: '检查清单,选择列表'},
          {id: 18, name: 'delete', codename: '&#xe810;', tag: '删除,清除'},
          {id: 19, name: 'directionLtr', codename: '&#xe810;', tag: '文本方向从左到右'},
          {id: 20, name: 'directionLtr2', codename: '&#xe810;', tag: '文本方向从左到右'},
          {id: 21, name: 'directionRtl', codename: '&#xe810;', tag: '文本方向从右到左'},
          {id: 22, name: 'directionRtl2', codename: '&#xe810;', tag: '文本方向从右到左'},
          {id: 23, name: 'edit', codename: '&#xe810;', tag: '编辑'},
          {id: 24, name: 'edit2', codename: '&#xe810;', tag: '编辑'},
          {id: 25, name: 'ellipsis', codename: '&#xe810;', tag: '省略,省略号,更多,菜单'},
          {id: 26, name: 'ellipsisVertical', codename: '&#xe810;', tag: '省略,省略号,更多,菜单'},
          {id: 27, name: 'font', codename: '&#xe810;', tag: '字体'},
          {id: 28, name: 'fontColor', codename: '&#xe810;', tag: '字体颜色'},
          {id: 29, name: 'fontSize', codename: '&#xe810;', tag: '字体大小'},
          {id: 30, name: 'fontSize2', codename: '&#xe810;', tag: '字体大小'},
          {id: 31, name: 'fontSizeDecrease', codename: '&#xe810;', tag: '字体减小'},
          {id: 32, name: 'fontSizeIncrease', codename: '&#xe810;', tag: '字体增大'},
          {id: 33, name: 'formatClear', codename: '&#xe810;', tag: '格式清除'},
          {id: 34, name: 'indent', codename: '&#xe810;', tag: '缩进'},
          {id: 35, name: 'indent2', codename: '&#xe810;', tag: '缩进'},
          {id: 36, name: 'indentDecrease', codename: '&#xe810;', tag: '缩进减小'},
          {id: 37, name: 'indentDecrease2', codename: '&#xe810;', tag: '缩进减小'},
          {id: 38, name: 'indentIncrease', codename: '&#xe810;', tag: '缩进增大'},
          {id: 39, name: 'indentIncrease2', codename: '&#xe810;', tag: '缩进增大'},
          {id: 40, name: 'italic', codename: '&#xe810;', tag: '斜体'},
          {id: 41, name: 'lineSpacing', codename: '&#xe810;', tag: '行距'},
          {id: 42, name: 'link', codename: '&#xe810;', tag: '链接'},
          {id: 43, name: 'unlink', codename: '&#xe810;', tag: '取消链接'},
          {id: 44, name: 'list', codename: '&#xe810;', tag: '列表,清单'},
          {id: 45, name: 'list2', codename: '&#xe810;', tag: '列表,清单'},
          {id: 46, name: 'list3', codename: '&#xe810;', tag: '列表,清单'},
          {id: 47, name: 'list4', codename: '&#xe810;', tag: '列表,清单'},
          {id: 48, name: 'list5', codename: '&#xe810;', tag: '列表,清单'},
          {id: 49, name: 'list6', codename: '&#xe810;', tag: '列表,清单'},
          {id: 50, name: 'list7', codename: '&#xe810;', tag: '列表,清单'},
          {id: 51, name: 'list8', codename: '&#xe810;', tag: '列表,清单'},
          {id: 52, name: 'ul', codename: '&#xe810;', tag: '无序列表'},
          {id: 53, name: 'ol', codename: '&#xe810;', tag: '无序列表'},
          {id: 54, name: 'outdent', codename: '&#xe810;', tag: '减小缩进'},
          {id: 55, name: 'outdent2', codename: '&#xe810;', tag: '减小缩进'},
          {id: 56, name: 'pageBreak', codename: '&#xe810;', tag: '分页符'},
          {id: 57, name: 'paragraphMarginBottom', codename: '&#xe810;', tag: '段后距'},
          {id: 58, name: 'paragraphMarginTop', codename: '&#xe810;', tag: '段前距'},
          {id: 59, name: 'pilcrow', codename: '&#xe810;', tag: '段落符号'},
          {id: 60, name: 'quoteLeft', codename: '&#xe810;', tag: '引用左'},
          {id: 61, name: 'quoteRight', codename: '&#xe810;', tag: '引用右'},
          {id: 62, name: 'rename', codename: '&#xe810;', tag: '重命名'},
          {id: 63, name: 'strikethrough', codename: '&#xe810;', tag: '删除线'},
          {id: 64, name: 'strikethrough2', codename: '&#xe810;', tag: '删除线'},
          {id: 65, name: 'subscript', codename: '&#xe810;', tag: '下标'},
          {id: 66, name: 'superscript', codename: '&#xe810;', tag: '上标'},
          {id: 67, name: 'table', codename: '&#xe810;', tag: '表格'},
          {id: 68, name: 'textAlignCenter', codename: '&#xe810;', tag: '居中对齐文本'},
          {id: 69, name: 'textAlignCenter2', codename: '&#xe810;', tag: '居中对齐文本'},
          {id: 70, name: 'textAlignJustify', codename: '&#xe810;', tag: '全部两端对齐'},
          {id: 71, name: 'textAlignJustifyLC', codename: '&#xe810;', tag: '两端对齐，末行居中对齐'},
          {id: 72, name: 'textAlignJustifyLL', codename: '&#xe810;', tag: '两端对齐，末行左对齐'},
          {id: 73, name: 'textAlignJustifyLR', codename: '&#xe810;', tag: '两端对齐，末行右对齐'},
          {id: 74, name: 'textAlignLeft', codename: '&#xe810;', tag: '左对齐文本'},
          {id: 75, name: 'textAlignLeft2', codename: '&#xe810;', tag: '左对齐文本'},
          {id: 76, name: 'textAlignRight', codename: '&#xe810;', tag: '右对齐文本'},
          {id: 77, name: 'textAlignRight2', codename: '&#xe810;', tag: '右对齐文本'},
          {id: 78, name: 'textAround', codename: '&#xe810;', tag: '文本环绕'},
          {id: 79, name: 'textIndent', codename: '&#xe810;', tag: '首行缩进'},
          {id: 80, name: 'textTransform', codename: '&#xe810;', tag: '字母大写'},
          {id: 81, name: 'title', codename: '&#xe810;', tag: '标题'},
          {id: 82, name: 'underline', codename: '&#xe810;', tag: '下划线'}
        ]
      },
      {
        id: 20,
        title: '8-1-Users & People（用户 & 人）',
        content: [
          {id: 1, name: 'contacts', codename: '&#xe812;', tag: '联络,通讯录'},
          {id: 2, name: 'contacts2', codename: '&#xe810;', tag: '联络,通讯录'},
          {id: 3, name: 'portraitMale', codename: '&#xe814;', tag: '用户,人,男性肖像'},
          {id: 4, name: 'portraitMale2', codename: '&#xe811;', tag: '用户,人,男性肖像'},
          {id: 5, name: 'portraitMale3', codename: '&#xe813;', tag: '用户,人,男性肖像'},
          {id: 6, name: 'portraitMaleInfo', codename: '&#xe815;', tag: '用户,人,男性肖像,用户信息'},
          {id: 7, name: 'portraitMaleInfo2', codename: '&#xe815;', tag: '用户,人,男性肖像,用户信息'},
          {id: 8, name: 'portraitMaleInfo3', codename: '&#xe815;', tag: '用户,人,男性肖像,用户信息'},
          {id: 9, name: 'portraitMalePlus', codename: '&#xe815;', tag: '添加用户,用户,人,男性肖像'},
          {id: 10, name: 'portraitMalePlus2', codename: '&#xe815;', tag: '添加用户,用户,人,男性肖像'},
          {id: 11, name: 'portraitMalePlus3', codename: '&#xe815;', tag: '添加用户,用户,人,男性肖像'},
          {id: 12, name: 'portraitMalePlus4', codename: '&#xe815;', tag: '添加用户,用户,人,男性肖像'},
          {id: 13, name: 'portraitMalePlus5', codename: '&#xe815;', tag: '添加用户,用户,人,男性肖像'},
          {id: 14, name: 'portraitMalePlus6', codename: '&#xe815;', tag: '添加用户,用户,人,男性肖像'},
          {id: 15, name: 'user', codename: '&#xe815;', tag: '用户'},
          {id: 16, name: 'user2', codename: '&#xe815;', tag: '用户'},
          {id: 17, name: 'userGroup', codename: '&#xe815;', tag: '用户组,组'},
          {id: 18, name: 'userGroup2', codename: '&#xe815;', tag: '用户组,组'},
          {id: 19, name: 'userGroupMinus', codename: '&#xe815;', tag: '删除用户组,删除组'},
          {id: 20, name: 'userGroupMinus2', codename: '&#xe815;', tag: '删除用户组,删除组'},
          {id: 21, name: 'userGroupPlus', codename: '&#xe815;', tag: '添加用户组,添加组'},
          {id: 22, name: 'userGroupPlus2', codename: '&#xe815;', tag: '添加用户组,添加组'},
          {id: 23, name: 'userMinus', codename: '&#xe815;', tag: '删除用户'},
          {id: 24, name: 'userMinus2', codename: '&#xe815;', tag: '删除用户'},
          {id: 25, name: 'userPlus', codename: '&#xe815;', tag: '添加用户'},
          {id: 26, name: 'userPlus2', codename: '&#xe815;', tag: '添加用户'}
        ]
      },
      {
        id: 21,
        title: '8-3-Hand & Touch Gestures（手 & 触摸手势）',
        content: [
          {id: 1, name: 'thumbsDown', codename: '&#xe812;', tag: '拇指向下,反对,不支持,抵制'},
          {id: 2, name: 'thumbsDown2', codename: '&#xe810;', tag: '拇指向下,反对,不支持,抵制'},
          {id: 3, name: 'thumbsUp', codename: '&#xe814;', tag: '竖起大拇指,点赞,支持'},
          {id: 4, name: 'thumbsUp2', codename: '&#xe811;', tag: '竖起大拇指,点赞,支持'}
        ]
      },
      {
        id: 22,
        title: '10-1-Navigation & Location（导航 & 定位）',
        content: [
          {id: 1, name: 'mapMarker', codename: '&#xe812;', tag: '地图标记,定位'}
        ]
      },
      {
        id: 23,
        title: '13-1-Date & Time（日期 & 时间）',
        content: [
          {id: 1, name: 'calendar', codename: '&#xe812;', tag: '日历,日期'},
          {id: 2, name: 'clockCircle', codename: '&#xe812;', tag: '时钟,时间'},
          {id: 3, name: 'clockSquare', codename: '&#xe812;', tag: '时钟,时间'},
          {id: 4, name: 'hourglass', codename: '&#xe812;', tag: '沙漏'}
        ]
      },
      {
        id: 24,
        title: '13-3-Trash & Recycle（垃圾 & 回收）',
        content: [
          {id: 1, name: 'trash', codename: '&#xe812;', tag: '垃圾桶,删除,清除'},
          {id: 2, name: 'trash2', codename: '&#xe812;', tag: '垃圾桶,删除,清除'}
        ]
      },
      {
        id: 25,
        title: '16-1-Arrows（箭头）',
        content: [
          {id: 1, name: 'arrowDown', codename: '&#xe812;', tag: '箭头向下'},
          {id: 2, name: 'arrowDown2', codename: '&#xe810;', tag: '箭头向下'},
          {id: 3, name: 'arrowDown3', codename: '&#xe814;', tag: '箭头向下'},
          {id: 4, name: 'arrowLd', codename: '&#xe811;', tag: '箭头,左下箭头'},
          {id: 5, name: 'arrowLeft', codename: '&#xe813;', tag: '箭头向左'},
          {id: 6, name: 'arrowLeft2', codename: '&#xe815;', tag: '箭头向左'},
          {id: 7, name: 'arrowLeft3', codename: '&#xe815;', tag: '箭头向左'},
          {id: 8, name: 'arrowLu', codename: '&#xe815;', tag: '箭头,左上箭头'},
          {id: 9, name: 'arrowRd', codename: '&#xe815;', tag: '箭头,右下箭头'},
          {id: 10, name: 'arrowRight', codename: '&#xe815;', tag: '箭头向右'},
          {id: 11, name: 'arrowRight2', codename: '&#xe815;', tag: '箭头向右'},
          {id: 12, name: 'arrowRight3', codename: '&#xe815;', tag: '箭头向右'},
          {id: 13, name: 'arrowRu', codename: '&#xe815;', tag: '箭头,右上箭头'},
          {id: 14, name: 'arrowUp', codename: '&#xe815;', tag: '箭头向上'},
          {id: 15, name: 'arrowUp2', codename: '&#xe815;', tag: '箭头向上'},
          {id: 16, name: 'arrowUp3', codename: '&#xe815;', tag: '箭头向上'},
          {id: 17, name: 'download', codename: '&#xe815;', tag: '下载'},
          {id: 18, name: 'enter', codename: '&#xe815;', tag: '进入,入口'},
          {id: 19, name: 'enter2', codename: '&#xe815;', tag: '进入,回车,回车符'},
          {id: 20, name: 'exit', codename: '&#xe815;', tag: '离开,出口'},
          {id: 21, name: 'expand', codename: '&#xe815;', tag: '扩展,扩大,箭头'},
          {id: 22, name: 'expand2', codename: '&#xe815;', tag: '扩展,扩大,箭头'},
          {id: 23, name: 'expandHorizontal', codename: '&#xe815;', tag: '扩展水平'},
          {id: 24, name: 'expandHorizontal2', codename: '&#xe815;', tag: '扩展水平'},
          {id: 25, name: 'expandVertical', codename: '&#xe815;', tag: '扩展垂直'},
          {id: 26, name: 'expandVertical2', codename: '&#xe815;', tag: '扩展垂直'},
          {id: 27, name: 'external', codename: '&#xe815;', tag: '外面的,外部的,导出'},
          {id: 28, name: 'extractDown', codename: '&#xe815;', tag: '提取下,退出,离开'},
          {id: 29, name: 'extractLeft', codename: '&#xe815;', tag: '提取左,退出,离开'},
          {id: 30, name: 'extractRight', codename: '&#xe815;', tag: '提取右,退出,离开'},
          {id: 31, name: 'extractUp', codename: '&#xe815;', tag: '提取上,退出,离开'},
          {id: 32, name: 'insertDown', codename: '&#xe815;', tag: '插入下,进入'},
          {id: 33, name: 'insertLeft', codename: '&#xe815;', tag: '插入左,进入'},
          {id: 34, name: 'insertRight', codename: '&#xe815;', tag: '插入右,进入'},
          {id: 35, name: 'insertUp', codename: '&#xe815;', tag: '插入上,进入'},
          {id: 36, name: 'merge', codename: '&#xe815;', tag: '合并,合并箭头,箭头'},
          {id: 37, name: 'merge2', codename: '&#xe815;', tag: '合并,合并箭头,箭头'},
          {id: 38, name: 'merge3', codename: '&#xe815;', tag: '合并,合并箭头,箭头'},
          {id: 39, name: 'move', codename: '&#xe815;', tag: '移动,移动箭头,箭头'},
          {id: 40, name: 'redo', codename: '&#xe815;', tag: '重做'},
          {id: 41, name: 'redo2', codename: '&#xe815;', tag: '重做'},
          {id: 42, name: 'redo3', codename: '&#xe815;', tag: '重做'},
          {id: 43, name: 'refresh', codename: '&#xe815;', tag: '刷新,同步'},
          {id: 44, name: 'shrink', codename: '&#xe815;', tag: '收缩,缩小,箭头'},
          {id: 45, name: 'shrink2', codename: '&#xe815;', tag: '收缩,缩小,箭头'},
          {id: 46, name: 'shrinkHorizontal', codename: '&#xe815;', tag: '收缩水平'},
          {id: 47, name: 'shrinkHorizontal2', codename: '&#xe815;', tag: '收缩水平'},
          {id: 48, name: 'shrinkVertical', codename: '&#xe815;', tag: '收缩垂直'},
          {id: 49, name: 'shrinkVertical2', codename: '&#xe815;', tag: '收缩垂直'},
          {id: 50, name: 'split', codename: '&#xe815;', tag: '分裂,分开,分裂箭头,箭头'},
          {id: 51, name: 'split2', codename: '&#xe815;', tag: '分裂,分开,分裂箭头,箭头'},
          {id: 52, name: 'split3', codename: '&#xe815;', tag: '分裂,分开,分裂箭头,箭头'},
          {id: 53, name: 'swapHorizontal', codename: '&#xe815;', tag: '切换,水平切换'},
          {id: 54, name: 'swapHorizontal2', codename: '&#xe815;', tag: '切换,水平切换'},
          {id: 55, name: 'swapHorizontal3', codename: '&#xe815;', tag: '切换,水平切换,切换排序,水平切换排序'},
          {id: 56, name: 'swapVertical', codename: '&#xe815;', tag: '切换,垂直切换'},
          {id: 57, name: 'swapVertical2', codename: '&#xe815;', tag: '切换,垂直切换'},
          {id: 58, name: 'swapVertical3', codename: '&#xe815;', tag: '切换,垂直切换,切换排序,垂直切换排序'},
          {id: 59, name: 'tab', codename: '&#xe815;', tag: '标签,制表,制表符,选项卡'},
          {id: 60, name: 'tab2', codename: '&#xe815;', tag: '标签,制表,制表符,选项卡'},
          {id: 61, name: 'undo', codename: '&#xe815;', tag: '撤销'},
          {id: 62, name: 'undo2', codename: '&#xe815;', tag: '撤销'},
          {id: 63, name: 'undo3', codename: '&#xe815;', tag: '撤销'},
          {id: 64, name: 'upload', codename: '&#xe815;', tag: '上传'}
        ]
      },
      {
        id: 26,
        title: '20-Mobius英文字体设计',
        content: [
          {id: 1, name: 'A', codename: '&#xe812;', tag: '字母A'},
          {id: 2, name: 'B', codename: '&#xe810;', tag: '字母B'},
          {id: 3, name: 'C', codename: '&#xe814;', tag: '字母C'},
          {id: 4, name: 'D', codename: '&#xe811;', tag: '字母D'},
          {id: 5, name: 'E', codename: '&#xe813;', tag: '字母E'},
          {id: 6, name: 'F', codename: '&#xe815;', tag: '字母F'},
          {id: 7, name: 'G', codename: '&#xe815;', tag: '字母G'},
          {id: 8, name: 'H', codename: '&#xe815;', tag: '字母H'},
          {id: 9, name: 'I', codename: '&#xe815;', tag: '字母I'},
          {id: 10, name: 'J', codename: '&#xe815;', tag: '字母J'},
          {id: 11, name: 'K', codename: '&#xe815;', tag: '字母K'},
          {id: 12, name: 'L', codename: '&#xe815;', tag: '字母L'},
          {id: 13, name: 'M', codename: '&#xe815;', tag: '字母M'},
          {id: 14, name: 'M', codename: '&#xe815;', tag: '字母N'},
          {id: 15, name: 'O', codename: '&#xe815;', tag: '字母O'},
          {id: 16, name: 'P', codename: '&#xe815;', tag: '字母P'},
          {id: 17, name: 'Q', codename: '&#xe815;', tag: '字母Q'},
          {id: 18, name: 'R', codename: '&#xe815;', tag: '字母R'},
          {id: 19, name: 'S', codename: '&#xe815;', tag: '字母S'},
          {id: 20, name: 'T', codename: '&#xe815;', tag: '字母T'},
          {id: 21, name: 'U', codename: '&#xe815;', tag: '字母U'},
          {id: 22, name: 'V', codename: '&#xe815;', tag: '字母V'},
          {id: 23, name: 'W', codename: '&#xe815;', tag: '字母W'},
          {id: 24, name: 'X', codename: '&#xe815;', tag: '字母X'},
          {id: 25, name: 'Y', codename: '&#xe815;', tag: '字母Y'},
          {id: 26, name: 'Z', codename: '&#xe815;', tag: '字母Z'},
          {id: 27, name: '0', codename: '&#xe815;', tag: '数字0'},
          {id: 28, name: '1', codename: '&#xe815;', tag: '数字1'},
          {id: 29, name: '2', codename: '&#xe815;', tag: '数字2'},
          {id: 30, name: '3', codename: '&#xe815;', tag: '数字3'},
          {id: 31, name: '4', codename: '&#xe815;', tag: '数字4'},
          {id: 32, name: '5', codename: '&#xe815;', tag: '数字5'},
          {id: 33, name: '6', codename: '&#xe815;', tag: '数字6'},
          {id: 34, name: '7', codename: '&#xe815;', tag: '数字7'},
          {id: 35, name: '8', codename: '&#xe815;', tag: '数字8'},
          {id: 36, name: '9', codename: '&#xe815;', tag: '数字9'},
          {id: 37, name: 'comma', codename: '&#xe815;', tag: '逗号'},
          {id: 38, name: 'period', codename: '&#xe815;', tag: '句号'},
          {id: 39, name: 'colon', codename: '&#xe815;', tag: '冒号'},
          {id: 40, name: 'semicolon', codename: '&#xe815;', tag: '分号'},
          {id: 41, name: 'exclamation', codename: '&#xe815;', tag: '感叹号'},
          {id: 42, name: 'questionMark', codename: '&#xe815;', tag: '问号'},
          {id: 43, name: 'quoteLeft', codename: '&#xe815;', tag: '左引号'},
          {id: 44, name: 'quoteRight', codename: '&#xe815;', tag: '右引号'},
          {id: 45, name: 'ellipsis', codename: '&#xe815;', tag: '省略号'},
          {id: 46, name: 'hyphen', codename: '&#xe815;', tag: '连字符'}
        ]
      }
    ]
  },
  methods: {
    /*getjson() {
      axios.post('iconfont.json', {
          firstName: 'Fred',
          lastName: 'Flintstone'
        })
        .then(function (response) {
          console.log(response);
          alert('saa');
        })
        .catch(function (error) {
          console.log(error);
        });
    }*/
    checkItem(index) {
      this.isActive = index;
      this.grid = this.tabs[index].grid;
    },
    changeIconfontSize(fontSize) {
      this.iconfontStyle = {'font-size': `${fontSize}rem`};
    },
    changeFocus(isF) {
      this.changeArrow = ['changeSize', 'f1', 'fb', 'ali_ite_cen', isF? 'focus':''];
    }
  },
  components: {
    iconfont: {
      template: '#iconfont',
      data() {
        return {
        }
      },
      props: [
        'iconfontlists',
        'grid',
        'istyle'
      ]
    }
  },
  created() {
    // this.getjson();
  },
});
